-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZ7k2GJZtFO1F5qOQ
m0XYd+VdOiGuuDLf+qXZoLDHl7OgCgYIKoZIzj0DAQehRANCAAQxhGQIuXLHF8Wu
4YzzGbWrhyBvLkZ2pPbnjCH7wi1D0xGFSxMSCl1wU/d7r2roci7lv7xCUJ+13nmD
vvkl/7Sy
-----END PRIVATE KEY-----