/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuardRouteImport } from './routes/guard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecurityIndexRouteImport } from './routes/security.index'
import { Route as GuardIndexRouteImport } from './routes/guard.index'
import { Route as GuardScheduleRouteImport } from './routes/guard.schedule'
import { Route as GuardRequestsRouteImport } from './routes/guard.requests'
import { Route as GuardPatrolRouteImport } from './routes/guard.patrol'
import { Route as GuardNotificationsRouteImport } from './routes/guard.notifications'
import { Route as GuardIncidentRouteImport } from './routes/guard.incident'
import { Route as GuardCheckOutRouteImport } from './routes/guard.check-out'
import { Route as GuardCheckInRouteImport } from './routes/guard.check-in'
import { Route as GuardAccountRouteImport } from './routes/guard.account'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardRoute = GuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityRoute,
} as any)
const GuardIndexRoute = GuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardRoute,
} as any)
const GuardScheduleRoute = GuardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => GuardRoute,
} as any)
const GuardRequestsRoute = GuardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => GuardRoute,
} as any)
const GuardPatrolRoute = GuardPatrolRouteImport.update({
  id: '/patrol',
  path: '/patrol',
  getParentRoute: () => GuardRoute,
} as any)
const GuardNotificationsRoute = GuardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => GuardRoute,
} as any)
const GuardIncidentRoute = GuardIncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => GuardRoute,
} as any)
const GuardCheckOutRoute = GuardCheckOutRouteImport.update({
  id: '/check-out',
  path: '/check-out',
  getParentRoute: () => GuardRoute,
} as any)
const GuardCheckInRoute = GuardCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => GuardRoute,
} as any)
const GuardAccountRoute = GuardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => GuardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guard': typeof GuardRouteWithChildren
  '/login': typeof LoginRoute
  '/security': typeof SecurityRouteWithChildren
  '/guard/account': typeof GuardAccountRoute
  '/guard/check-in': typeof GuardCheckInRoute
  '/guard/check-out': typeof GuardCheckOutRoute
  '/guard/incident': typeof GuardIncidentRoute
  '/guard/notifications': typeof GuardNotificationsRoute
  '/guard/patrol': typeof GuardPatrolRoute
  '/guard/requests': typeof GuardRequestsRoute
  '/guard/schedule': typeof GuardScheduleRoute
  '/guard/': typeof GuardIndexRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/guard/account': typeof GuardAccountRoute
  '/guard/check-in': typeof GuardCheckInRoute
  '/guard/check-out': typeof GuardCheckOutRoute
  '/guard/incident': typeof GuardIncidentRoute
  '/guard/notifications': typeof GuardNotificationsRoute
  '/guard/patrol': typeof GuardPatrolRoute
  '/guard/requests': typeof GuardRequestsRoute
  '/guard/schedule': typeof GuardScheduleRoute
  '/guard': typeof GuardIndexRoute
  '/security': typeof SecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guard': typeof GuardRouteWithChildren
  '/login': typeof LoginRoute
  '/security': typeof SecurityRouteWithChildren
  '/guard/account': typeof GuardAccountRoute
  '/guard/check-in': typeof GuardCheckInRoute
  '/guard/check-out': typeof GuardCheckOutRoute
  '/guard/incident': typeof GuardIncidentRoute
  '/guard/notifications': typeof GuardNotificationsRoute
  '/guard/patrol': typeof GuardPatrolRoute
  '/guard/requests': typeof GuardRequestsRoute
  '/guard/schedule': typeof GuardScheduleRoute
  '/guard/': typeof GuardIndexRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guard'
    | '/login'
    | '/security'
    | '/guard/account'
    | '/guard/check-in'
    | '/guard/check-out'
    | '/guard/incident'
    | '/guard/notifications'
    | '/guard/patrol'
    | '/guard/requests'
    | '/guard/schedule'
    | '/guard/'
    | '/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/guard/account'
    | '/guard/check-in'
    | '/guard/check-out'
    | '/guard/incident'
    | '/guard/notifications'
    | '/guard/patrol'
    | '/guard/requests'
    | '/guard/schedule'
    | '/guard'
    | '/security'
  id:
    | '__root__'
    | '/'
    | '/guard'
    | '/login'
    | '/security'
    | '/guard/account'
    | '/guard/check-in'
    | '/guard/check-out'
    | '/guard/incident'
    | '/guard/notifications'
    | '/guard/patrol'
    | '/guard/requests'
    | '/guard/schedule'
    | '/guard/'
    | '/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuardRoute: typeof GuardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SecurityRoute: typeof SecurityRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guard': {
      id: '/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof GuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/guard/': {
      id: '/guard/'
      path: '/'
      fullPath: '/guard/'
      preLoaderRoute: typeof GuardIndexRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/schedule': {
      id: '/guard/schedule'
      path: '/schedule'
      fullPath: '/guard/schedule'
      preLoaderRoute: typeof GuardScheduleRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/requests': {
      id: '/guard/requests'
      path: '/requests'
      fullPath: '/guard/requests'
      preLoaderRoute: typeof GuardRequestsRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/patrol': {
      id: '/guard/patrol'
      path: '/patrol'
      fullPath: '/guard/patrol'
      preLoaderRoute: typeof GuardPatrolRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/notifications': {
      id: '/guard/notifications'
      path: '/notifications'
      fullPath: '/guard/notifications'
      preLoaderRoute: typeof GuardNotificationsRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/incident': {
      id: '/guard/incident'
      path: '/incident'
      fullPath: '/guard/incident'
      preLoaderRoute: typeof GuardIncidentRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/check-out': {
      id: '/guard/check-out'
      path: '/check-out'
      fullPath: '/guard/check-out'
      preLoaderRoute: typeof GuardCheckOutRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/check-in': {
      id: '/guard/check-in'
      path: '/check-in'
      fullPath: '/guard/check-in'
      preLoaderRoute: typeof GuardCheckInRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/account': {
      id: '/guard/account'
      path: '/account'
      fullPath: '/guard/account'
      preLoaderRoute: typeof GuardAccountRouteImport
      parentRoute: typeof GuardRoute
    }
  }
}

interface GuardRouteChildren {
  GuardAccountRoute: typeof GuardAccountRoute
  GuardCheckInRoute: typeof GuardCheckInRoute
  GuardCheckOutRoute: typeof GuardCheckOutRoute
  GuardIncidentRoute: typeof GuardIncidentRoute
  GuardNotificationsRoute: typeof GuardNotificationsRoute
  GuardPatrolRoute: typeof GuardPatrolRoute
  GuardRequestsRoute: typeof GuardRequestsRoute
  GuardScheduleRoute: typeof GuardScheduleRoute
  GuardIndexRoute: typeof GuardIndexRoute
}

const GuardRouteChildren: GuardRouteChildren = {
  GuardAccountRoute: GuardAccountRoute,
  GuardCheckInRoute: GuardCheckInRoute,
  GuardCheckOutRoute: GuardCheckOutRoute,
  GuardIncidentRoute: GuardIncidentRoute,
  GuardNotificationsRoute: GuardNotificationsRoute,
  GuardPatrolRoute: GuardPatrolRoute,
  GuardRequestsRoute: GuardRequestsRoute,
  GuardScheduleRoute: GuardScheduleRoute,
  GuardIndexRoute: GuardIndexRoute,
}

const GuardRouteWithChildren = GuardRoute._addFileChildren(GuardRouteChildren)

interface SecurityRouteChildren {
  SecurityIndexRoute: typeof SecurityIndexRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityIndexRoute: SecurityIndexRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuardRoute: GuardRouteWithChildren,
  LoginRoute: LoginRoute,
  SecurityRoute: SecurityRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
