/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as ThucPhamRouteImport } from './routes/thuc-pham'
import { Route as ThongBaoRouteImport } from './routes/thong-bao'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as SucKhoeRouteImport } from './routes/suc-khoe'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuanLyGiupViecRouteImport } from './routes/quan-ly-giup-viec'
import { Route as QrVaoRaRouteImport } from './routes/qr-vao-ra'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as LichGiaDinhRouteImport } from './routes/lich-gia-dinh'
import { Route as KyNiemGiaDinhRouteImport } from './routes/ky-niem-gia-dinh'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GiaDinhRouteImport } from './routes/gia-dinh'
import { Route as GuardRouteImport } from './routes/guard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DuLichRouteImport } from './routes/du-lich'
import { Route as DichVuRouteImport } from './routes/dich-vu'
import { Route as DemoLoginRouteImport } from './routes/demo-login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as CongDongRouteImport } from './routes/cong-dong'
import { Route as ConCaiRouteImport } from './routes/con-cai'
import { Route as ChiTieuRouteImport } from './routes/chi-tieu'
import { Route as ChamSocOngBaRouteImport } from './routes/cham-soc-ong-ba'
import { Route as BqlRouteImport } from './routes/bql'
import { Route as BaoAnRouteImport } from './routes/bao-an'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecurityIndexRouteImport } from './routes/security.index'
import { Route as GuardIndexRouteImport } from './routes/guard.index'
import { Route as GuardPatrolRouteImport } from './routes/guard.patrol'
import { Route as GuardScanRouteImport } from './routes/guard.scan'
import { Route as GuardTasksRouteImport } from './routes/guard.tasks'
import { Route as GuardMeRouteImport } from './routes/guard.me'
import { Route as SaasIndexRouteImport } from './routes/saas.index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as FamilyIndexRouteImport } from './routes/family.index'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as BqlIndexRouteImport } from './routes/bql.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SucKhoeQuanLyRouteImport } from './routes/suc-khoe.quan-ly'
import { Route as SaasUsersRouteImport } from './routes/saas.users'
import { Route as SaasTenantsRouteImport } from './routes/saas.tenants'
import { Route as SaasProjectsRouteImport } from './routes/saas.projects'
import { Route as SaasPlansRouteImport } from './routes/saas.plans'
import { Route as SaasLeadsRouteImport } from './routes/saas.leads'
import { Route as SaasIncidentsRouteImport } from './routes/saas.incidents'
import { Route as SaasFeatureFlagsRouteImport } from './routes/saas.feature-flags'
import { Route as SaasCaiDatRouteImport } from './routes/saas.cai-dat'
import { Route as SaasBillingRouteImport } from './routes/saas.billing'
import { Route as SaasAuditRouteImport } from './routes/saas.audit'
import { Route as OpsWorkOrdersRouteImport } from './routes/ops.work-orders'
import { Route as OpsSlaRouteImport } from './routes/ops.sla'
import { Route as OpsOccupancyRouteImport } from './routes/ops.occupancy'
import { Route as OpsFeeRouteImport } from './routes/ops.fee'
import { Route as OpsComplaintsRouteImport } from './routes/ops.complaints'
import { Route as ChiTieuScanRouteImport } from './routes/chi-tieu_.scan'
import { Route as ChamSocOngBaNhatKyRouteImport } from './routes/cham-soc-ong-ba.nhat-ky'
import { Route as CaiDatThongBaoRouteImport } from './routes/cai-dat.thong-bao'
import { Route as BqlYeuCauRouteImport } from './routes/bql.yeu-cau'
import { Route as BqlToaNhaRouteImport } from './routes/bql.toa-nha'
import { Route as BqlThongBaoRouteImport } from './routes/bql.thong-bao'
import { Route as BqlThanhToanRouteImport } from './routes/bql.thanh-toan'
import { Route as BqlSuCoRouteImport } from './routes/bql.su-co'
import { Route as BqlPhiDichVuRouteImport } from './routes/bql.phi-dich-vu'
import { Route as BqlPhanAnhRouteImport } from './routes/bql.phan-anh'
import { Route as BqlNhanSuRouteImport } from './routes/bql.nhan-su'
import { Route as BqlKhachXeRouteImport } from './routes/bql.khach-xe'
import { Route as BqlHoGiaDinhRouteImport } from './routes/bql.ho-gia-dinh'
import { Route as BqlDuAnRouteImport } from './routes/bql.du-an'
import { Route as BqlCuDanRouteImport } from './routes/bql.cu-dan'
import { Route as BqlCanHoRouteImport } from './routes/bql.can-ho'
import { Route as BqlCaiDatRouteImport } from './routes/bql.cai-dat'
import { Route as BqlBaoTriRouteImport } from './routes/bql.bao-tri'
import { Route as BqlBaoCaoRouteImport } from './routes/bql.bao-cao'
import { Route as BqlAnNinhRouteImport } from './routes/bql.an-ninh'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSuperRouteImport } from './routes/admin.super'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminMemoriesRouteImport } from './routes/admin.memories'
import { Route as AdminHelpersRouteImport } from './routes/admin.helpers'
import { Route as AdminFamilyRouteImport } from './routes/admin.family'
import { Route as AdminElderlyCareRouteImport } from './routes/admin.elderly-care'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ConsoleMetricsKeyRouteImport } from './routes/console.metrics.$key'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ThucPhamRoute = ThucPhamRouteImport.update({
  id: '/thuc-pham',
  path: '/thuc-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const ThongBaoRoute = ThongBaoRouteImport.update({
  id: '/thong-bao',
  path: '/thong-bao',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const SucKhoeRoute = SucKhoeRouteImport.update({
  id: '/suc-khoe',
  path: '/suc-khoe',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyGiupViecRoute = QuanLyGiupViecRouteImport.update({
  id: '/quan-ly-giup-viec',
  path: '/quan-ly-giup-viec',
  getParentRoute: () => rootRouteImport,
} as any)
const QrVaoRaRoute = QrVaoRaRouteImport.update({
  id: '/qr-vao-ra',
  path: '/qr-vao-ra',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const LichGiaDinhRoute = LichGiaDinhRouteImport.update({
  id: '/lich-gia-dinh',
  path: '/lich-gia-dinh',
  getParentRoute: () => rootRouteImport,
} as any)
const KyNiemGiaDinhRoute = KyNiemGiaDinhRouteImport.update({
  id: '/ky-niem-gia-dinh',
  path: '/ky-niem-gia-dinh',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaDinhRoute = GiaDinhRouteImport.update({
  id: '/gia-dinh',
  path: '/gia-dinh',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardRoute = GuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DuLichRoute = DuLichRouteImport.update({
  id: '/du-lich',
  path: '/du-lich',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuRoute = DichVuRouteImport.update({
  id: '/dich-vu',
  path: '/dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLoginRoute = DemoLoginRouteImport.update({
  id: '/demo-login',
  path: '/demo-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const CongDongRoute = CongDongRouteImport.update({
  id: '/cong-dong',
  path: '/cong-dong',
  getParentRoute: () => rootRouteImport,
} as any)
const ConCaiRoute = ConCaiRouteImport.update({
  id: '/con-cai',
  path: '/con-cai',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiTieuRoute = ChiTieuRouteImport.update({
  id: '/chi-tieu',
  path: '/chi-tieu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamSocOngBaRoute = ChamSocOngBaRouteImport.update({
  id: '/cham-soc-ong-ba',
  path: '/cham-soc-ong-ba',
  getParentRoute: () => rootRouteImport,
} as any)
const BqlRoute = BqlRouteImport.update({
  id: '/bql',
  path: '/bql',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoAnRoute = BaoAnRouteImport.update({
  id: '/bao-an',
  path: '/bao-an',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityRoute,
} as any)
const GuardMeRoute = GuardMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => GuardRoute,
} as any)
const GuardTasksRoute = GuardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => GuardRoute,
} as any)
const GuardScanRoute = GuardScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => GuardRoute,
} as any)
const GuardPatrolRoute = GuardPatrolRouteImport.update({
  id: '/patrol',
  path: '/patrol',
  getParentRoute: () => GuardRoute,
} as any)
const GuardIndexRoute = GuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardRoute,
} as any)
const SaasIndexRoute = SaasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SaasRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamilyRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const BqlIndexRoute = BqlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BqlRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SucKhoeQuanLyRoute = SucKhoeQuanLyRouteImport.update({
  id: '/quan-ly',
  path: '/quan-ly',
  getParentRoute: () => SucKhoeRoute,
} as any)
const SaasUsersRoute = SaasUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SaasRoute,
} as any)
const SaasTenantsRoute = SaasTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SaasRoute,
} as any)
const SaasProjectsRoute = SaasProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SaasRoute,
} as any)
const SaasPlansRoute = SaasPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SaasRoute,
} as any)
const SaasLeadsRoute = SaasLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => SaasRoute,
} as any)
const SaasIncidentsRoute = SaasIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => SaasRoute,
} as any)
const SaasFeatureFlagsRoute = SaasFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => SaasRoute,
} as any)
const SaasCaiDatRoute = SaasCaiDatRouteImport.update({
  id: '/cai-dat',
  path: '/cai-dat',
  getParentRoute: () => SaasRoute,
} as any)
const SaasBillingRoute = SaasBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SaasRoute,
} as any)
const SaasAuditRoute = SaasAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SaasRoute,
} as any)
const OpsWorkOrdersRoute = OpsWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSlaRoute = OpsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => OpsRoute,
} as any)
const OpsOccupancyRoute = OpsOccupancyRouteImport.update({
  id: '/occupancy',
  path: '/occupancy',
  getParentRoute: () => OpsRoute,
} as any)
const OpsFeeRoute = OpsFeeRouteImport.update({
  id: '/fee',
  path: '/fee',
  getParentRoute: () => OpsRoute,
} as any)
const OpsComplaintsRoute = OpsComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => OpsRoute,
} as any)
const ChiTieuScanRoute = ChiTieuScanRouteImport.update({
  id: '/chi-tieu_/scan',
  path: '/chi-tieu/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamSocOngBaNhatKyRoute = ChamSocOngBaNhatKyRouteImport.update({
  id: '/nhat-ky',
  path: '/nhat-ky',
  getParentRoute: () => ChamSocOngBaRoute,
} as any)
const CaiDatThongBaoRoute = CaiDatThongBaoRouteImport.update({
  id: '/cai-dat/thong-bao',
  path: '/cai-dat/thong-bao',
  getParentRoute: () => rootRouteImport,
} as any)
const BqlYeuCauRoute = BqlYeuCauRouteImport.update({
  id: '/yeu-cau',
  path: '/yeu-cau',
  getParentRoute: () => BqlRoute,
} as any)
const BqlToaNhaRoute = BqlToaNhaRouteImport.update({
  id: '/toa-nha',
  path: '/toa-nha',
  getParentRoute: () => BqlRoute,
} as any)
const BqlThongBaoRoute = BqlThongBaoRouteImport.update({
  id: '/thong-bao',
  path: '/thong-bao',
  getParentRoute: () => BqlRoute,
} as any)
const BqlThanhToanRoute = BqlThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => BqlRoute,
} as any)
const BqlSuCoRoute = BqlSuCoRouteImport.update({
  id: '/su-co',
  path: '/su-co',
  getParentRoute: () => BqlRoute,
} as any)
const BqlPhiDichVuRoute = BqlPhiDichVuRouteImport.update({
  id: '/phi-dich-vu',
  path: '/phi-dich-vu',
  getParentRoute: () => BqlRoute,
} as any)
const BqlPhanAnhRoute = BqlPhanAnhRouteImport.update({
  id: '/phan-anh',
  path: '/phan-anh',
  getParentRoute: () => BqlRoute,
} as any)
const BqlNhanSuRoute = BqlNhanSuRouteImport.update({
  id: '/nhan-su',
  path: '/nhan-su',
  getParentRoute: () => BqlRoute,
} as any)
const BqlKhachXeRoute = BqlKhachXeRouteImport.update({
  id: '/khach-xe',
  path: '/khach-xe',
  getParentRoute: () => BqlRoute,
} as any)
const BqlHoGiaDinhRoute = BqlHoGiaDinhRouteImport.update({
  id: '/ho-gia-dinh',
  path: '/ho-gia-dinh',
  getParentRoute: () => BqlRoute,
} as any)
const BqlDuAnRoute = BqlDuAnRouteImport.update({
  id: '/du-an',
  path: '/du-an',
  getParentRoute: () => BqlRoute,
} as any)
const BqlCuDanRoute = BqlCuDanRouteImport.update({
  id: '/cu-dan',
  path: '/cu-dan',
  getParentRoute: () => BqlRoute,
} as any)
const BqlCanHoRoute = BqlCanHoRouteImport.update({
  id: '/can-ho',
  path: '/can-ho',
  getParentRoute: () => BqlRoute,
} as any)
const BqlCaiDatRoute = BqlCaiDatRouteImport.update({
  id: '/cai-dat',
  path: '/cai-dat',
  getParentRoute: () => BqlRoute,
} as any)
const BqlBaoTriRoute = BqlBaoTriRouteImport.update({
  id: '/bao-tri',
  path: '/bao-tri',
  getParentRoute: () => BqlRoute,
} as any)
const BqlBaoCaoRoute = BqlBaoCaoRouteImport.update({
  id: '/bao-cao',
  path: '/bao-cao',
  getParentRoute: () => BqlRoute,
} as any)
const BqlAnNinhRoute = BqlAnNinhRouteImport.update({
  id: '/an-ninh',
  path: '/an-ninh',
  getParentRoute: () => BqlRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuperRoute = AdminSuperRouteImport.update({
  id: '/admin/super',
  path: '/admin/super',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMemoriesRoute = AdminMemoriesRouteImport.update({
  id: '/admin/memories',
  path: '/admin/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHelpersRoute = AdminHelpersRouteImport.update({
  id: '/admin/helpers',
  path: '/admin/helpers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFamilyRoute = AdminFamilyRouteImport.update({
  id: '/admin/family',
  path: '/admin/family',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminElderlyCareRoute = AdminElderlyCareRouteImport.update({
  id: '/admin/elderly-care',
  path: '/admin/elderly-care',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/admin/calendar',
  path: '/admin/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleMetricsKeyRoute = ConsoleMetricsKeyRouteImport.update({
  id: '/metrics/$key',
  path: '/metrics/$key',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bao-an': typeof BaoAnRoute
  '/bql': typeof BqlRouteWithChildren
  '/cham-soc-ong-ba': typeof ChamSocOngBaRouteWithChildren
  '/chi-tieu': typeof ChiTieuRoute
  '/con-cai': typeof ConCaiRoute
  '/cong-dong': typeof CongDongRoute
  '/console': typeof ConsoleRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-login': typeof DemoLoginRoute
  '/dich-vu': typeof DichVuRoute
  '/du-lich': typeof DuLichRoute
  '/family': typeof FamilyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gia-dinh': typeof GiaDinhRoute
  '/guard': typeof GuardRouteWithChildren
  '/home': typeof HomeRoute
  '/ky-niem-gia-dinh': typeof KyNiemGiaDinhRoute
  '/lich-gia-dinh': typeof LichGiaDinhRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/portal': typeof PortalRoute
  '/qr-vao-ra': typeof QrVaoRaRoute
  '/quan-ly-giup-viec': typeof QuanLyGiupViecRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas': typeof SaasRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/suc-khoe': typeof SucKhoeRouteWithChildren
  '/tai-khoan': typeof TaiKhoanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/elderly-care': typeof AdminElderlyCareRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/memories': typeof AdminMemoriesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/super': typeof AdminSuperRoute
  '/admin/users': typeof AdminUsersRoute
  '/bql/an-ninh': typeof BqlAnNinhRoute
  '/bql/bao-cao': typeof BqlBaoCaoRoute
  '/bql/bao-tri': typeof BqlBaoTriRoute
  '/bql/cai-dat': typeof BqlCaiDatRoute
  '/bql/can-ho': typeof BqlCanHoRoute
  '/bql/cu-dan': typeof BqlCuDanRoute
  '/bql/du-an': typeof BqlDuAnRoute
  '/bql/ho-gia-dinh': typeof BqlHoGiaDinhRoute
  '/bql/khach-xe': typeof BqlKhachXeRoute
  '/bql/nhan-su': typeof BqlNhanSuRoute
  '/bql/phan-anh': typeof BqlPhanAnhRoute
  '/bql/phi-dich-vu': typeof BqlPhiDichVuRoute
  '/bql/su-co': typeof BqlSuCoRoute
  '/bql/thanh-toan': typeof BqlThanhToanRoute
  '/bql/thong-bao': typeof BqlThongBaoRoute
  '/bql/toa-nha': typeof BqlToaNhaRoute
  '/bql/yeu-cau': typeof BqlYeuCauRoute
  '/cai-dat/thong-bao': typeof CaiDatThongBaoRoute
  '/cham-soc-ong-ba/nhat-ky': typeof ChamSocOngBaNhatKyRoute
  '/chi-tieu/scan': typeof ChiTieuScanRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/fee': typeof OpsFeeRoute
  '/ops/occupancy': typeof OpsOccupancyRoute
  '/ops/sla': typeof OpsSlaRoute
  '/ops/work-orders': typeof OpsWorkOrdersRoute
  '/guard/me': typeof GuardMeRoute
  '/guard/patrol': typeof GuardPatrolRoute
  '/guard/scan': typeof GuardScanRoute
  '/guard/tasks': typeof GuardTasksRoute
  '/saas/audit': typeof SaasAuditRoute
  '/saas/billing': typeof SaasBillingRoute
  '/saas/cai-dat': typeof SaasCaiDatRoute
  '/saas/feature-flags': typeof SaasFeatureFlagsRoute
  '/saas/incidents': typeof SaasIncidentsRoute
  '/saas/leads': typeof SaasLeadsRoute
  '/saas/plans': typeof SaasPlansRoute
  '/saas/projects': typeof SaasProjectsRoute
  '/saas/tenants': typeof SaasTenantsRoute
  '/saas/users': typeof SaasUsersRoute
  '/suc-khoe/quan-ly': typeof SucKhoeQuanLyRoute
  '/admin/': typeof AdminIndexRoute
  '/bql/': typeof BqlIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/saas/': typeof SaasIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/guard/': typeof GuardIndexRoute
  '/console/metrics/$key': typeof ConsoleMetricsKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bao-an': typeof BaoAnRoute
  '/cham-soc-ong-ba': typeof ChamSocOngBaRouteWithChildren
  '/chi-tieu': typeof ChiTieuRoute
  '/con-cai': typeof ConCaiRoute
  '/cong-dong': typeof CongDongRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-login': typeof DemoLoginRoute
  '/dich-vu': typeof DichVuRoute
  '/du-lich': typeof DuLichRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gia-dinh': typeof GiaDinhRoute
  '/guard': typeof GuardRouteWithChildren
  '/home': typeof HomeRoute
  '/ky-niem-gia-dinh': typeof KyNiemGiaDinhRoute
  '/lich-gia-dinh': typeof LichGiaDinhRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/qr-vao-ra': typeof QrVaoRaRoute
  '/quan-ly-giup-viec': typeof QuanLyGiupViecRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suc-khoe': typeof SucKhoeRouteWithChildren
  '/tai-khoan': typeof TaiKhoanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/elderly-care': typeof AdminElderlyCareRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/memories': typeof AdminMemoriesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/super': typeof AdminSuperRoute
  '/admin/users': typeof AdminUsersRoute
  '/bql/an-ninh': typeof BqlAnNinhRoute
  '/bql/bao-cao': typeof BqlBaoCaoRoute
  '/bql/bao-tri': typeof BqlBaoTriRoute
  '/bql/cai-dat': typeof BqlCaiDatRoute
  '/bql/can-ho': typeof BqlCanHoRoute
  '/bql/cu-dan': typeof BqlCuDanRoute
  '/bql/du-an': typeof BqlDuAnRoute
  '/bql/ho-gia-dinh': typeof BqlHoGiaDinhRoute
  '/bql/khach-xe': typeof BqlKhachXeRoute
  '/bql/nhan-su': typeof BqlNhanSuRoute
  '/bql/phan-anh': typeof BqlPhanAnhRoute
  '/bql/phi-dich-vu': typeof BqlPhiDichVuRoute
  '/bql/su-co': typeof BqlSuCoRoute
  '/bql/thanh-toan': typeof BqlThanhToanRoute
  '/bql/thong-bao': typeof BqlThongBaoRoute
  '/bql/toa-nha': typeof BqlToaNhaRoute
  '/bql/yeu-cau': typeof BqlYeuCauRoute
  '/cai-dat/thong-bao': typeof CaiDatThongBaoRoute
  '/cham-soc-ong-ba/nhat-ky': typeof ChamSocOngBaNhatKyRoute
  '/chi-tieu/scan': typeof ChiTieuScanRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/fee': typeof OpsFeeRoute
  '/ops/occupancy': typeof OpsOccupancyRoute
  '/ops/sla': typeof OpsSlaRoute
  '/ops/work-orders': typeof OpsWorkOrdersRoute
  '/guard/me': typeof GuardMeRoute
  '/guard/patrol': typeof GuardPatrolRoute
  '/guard/scan': typeof GuardScanRoute
  '/guard/tasks': typeof GuardTasksRoute
  '/saas/audit': typeof SaasAuditRoute
  '/saas/billing': typeof SaasBillingRoute
  '/saas/cai-dat': typeof SaasCaiDatRoute
  '/saas/feature-flags': typeof SaasFeatureFlagsRoute
  '/saas/incidents': typeof SaasIncidentsRoute
  '/saas/leads': typeof SaasLeadsRoute
  '/saas/plans': typeof SaasPlansRoute
  '/saas/projects': typeof SaasProjectsRoute
  '/saas/tenants': typeof SaasTenantsRoute
  '/saas/users': typeof SaasUsersRoute
  '/suc-khoe/quan-ly': typeof SucKhoeQuanLyRoute
  '/admin': typeof AdminIndexRoute
  '/bql': typeof BqlIndexRoute
  '/console': typeof ConsoleIndexRoute
  '/family': typeof FamilyIndexRoute
  '/ops': typeof OpsIndexRoute
  '/saas': typeof SaasIndexRoute
  '/security': typeof SecurityIndexRoute
  '/console/metrics/$key': typeof ConsoleMetricsKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bao-an': typeof BaoAnRoute
  '/bql': typeof BqlRouteWithChildren
  '/cham-soc-ong-ba': typeof ChamSocOngBaRouteWithChildren
  '/chi-tieu': typeof ChiTieuRoute
  '/con-cai': typeof ConCaiRoute
  '/cong-dong': typeof CongDongRoute
  '/console': typeof ConsoleRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-login': typeof DemoLoginRoute
  '/dich-vu': typeof DichVuRoute
  '/du-lich': typeof DuLichRoute
  '/family': typeof FamilyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gia-dinh': typeof GiaDinhRoute
  '/guard': typeof GuardRouteWithChildren
  '/home': typeof HomeRoute
  '/ky-niem-gia-dinh': typeof KyNiemGiaDinhRoute
  '/lich-gia-dinh': typeof LichGiaDinhRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/portal': typeof PortalRoute
  '/qr-vao-ra': typeof QrVaoRaRoute
  '/quan-ly-giup-viec': typeof QuanLyGiupViecRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas': typeof SaasRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/suc-khoe': typeof SucKhoeRouteWithChildren
  '/tai-khoan': typeof TaiKhoanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/elderly-care': typeof AdminElderlyCareRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/memories': typeof AdminMemoriesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/super': typeof AdminSuperRoute
  '/admin/users': typeof AdminUsersRoute
  '/bql/an-ninh': typeof BqlAnNinhRoute
  '/bql/bao-cao': typeof BqlBaoCaoRoute
  '/bql/bao-tri': typeof BqlBaoTriRoute
  '/bql/cai-dat': typeof BqlCaiDatRoute
  '/bql/can-ho': typeof BqlCanHoRoute
  '/bql/cu-dan': typeof BqlCuDanRoute
  '/bql/du-an': typeof BqlDuAnRoute
  '/bql/ho-gia-dinh': typeof BqlHoGiaDinhRoute
  '/bql/khach-xe': typeof BqlKhachXeRoute
  '/bql/nhan-su': typeof BqlNhanSuRoute
  '/bql/phan-anh': typeof BqlPhanAnhRoute
  '/bql/phi-dich-vu': typeof BqlPhiDichVuRoute
  '/bql/su-co': typeof BqlSuCoRoute
  '/bql/thanh-toan': typeof BqlThanhToanRoute
  '/bql/thong-bao': typeof BqlThongBaoRoute
  '/bql/toa-nha': typeof BqlToaNhaRoute
  '/bql/yeu-cau': typeof BqlYeuCauRoute
  '/cai-dat/thong-bao': typeof CaiDatThongBaoRoute
  '/cham-soc-ong-ba/nhat-ky': typeof ChamSocOngBaNhatKyRoute
  '/chi-tieu_/scan': typeof ChiTieuScanRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/fee': typeof OpsFeeRoute
  '/ops/occupancy': typeof OpsOccupancyRoute
  '/ops/sla': typeof OpsSlaRoute
  '/ops/work-orders': typeof OpsWorkOrdersRoute
  '/guard/me': typeof GuardMeRoute
  '/guard/patrol': typeof GuardPatrolRoute
  '/guard/scan': typeof GuardScanRoute
  '/guard/tasks': typeof GuardTasksRoute
  '/saas/audit': typeof SaasAuditRoute
  '/saas/billing': typeof SaasBillingRoute
  '/saas/cai-dat': typeof SaasCaiDatRoute
  '/saas/feature-flags': typeof SaasFeatureFlagsRoute
  '/saas/incidents': typeof SaasIncidentsRoute
  '/saas/leads': typeof SaasLeadsRoute
  '/saas/plans': typeof SaasPlansRoute
  '/saas/projects': typeof SaasProjectsRoute
  '/saas/tenants': typeof SaasTenantsRoute
  '/saas/users': typeof SaasUsersRoute
  '/suc-khoe/quan-ly': typeof SucKhoeQuanLyRoute
  '/admin/': typeof AdminIndexRoute
  '/bql/': typeof BqlIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/saas/': typeof SaasIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/guard/': typeof GuardIndexRoute
  '/console/metrics/$key': typeof ConsoleMetricsKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bao-an'
    | '/bql'
    | '/cham-soc-ong-ba'
    | '/chi-tieu'
    | '/con-cai'
    | '/cong-dong'
    | '/console'
    | '/dashboard'
    | '/demo'
    | '/demo-login'
    | '/dich-vu'
    | '/du-lich'
    | '/family'
    | '/forgot-password'
    | '/gia-dinh'
    | '/home'
    | '/ky-niem-gia-dinh'
    | '/lich-gia-dinh'
    | '/lien-he'
    | '/login'
    | '/ops'
    | '/portal'
    | '/qr-vao-ra'
    | '/quan-ly-giup-viec'
    | '/reset-password'
    | '/saas'
    | '/security'
    | '/suc-khoe'
    | '/tai-khoan'
    | '/thong-bao'
    | '/thuc-pham'
    | '/workspaces'
    | '/admin/audit'
    | '/admin/calendar'
    | '/admin/elderly-care'
    | '/admin/family'
    | '/admin/helpers'
    | '/admin/memories'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/super'
    | '/admin/users'
    | '/bql/an-ninh'
    | '/bql/bao-cao'
    | '/bql/bao-tri'
    | '/bql/cai-dat'
    | '/bql/can-ho'
    | '/bql/cu-dan'
    | '/bql/du-an'
    | '/bql/ho-gia-dinh'
    | '/bql/khach-xe'
    | '/bql/nhan-su'
    | '/bql/phan-anh'
    | '/bql/phi-dich-vu'
    | '/bql/su-co'
    | '/bql/thanh-toan'
    | '/bql/thong-bao'
    | '/bql/toa-nha'
    | '/bql/yeu-cau'
    | '/cai-dat/thong-bao'
    | '/cham-soc-ong-ba/nhat-ky'
    | '/chi-tieu/scan'
    | '/ops/complaints'
    | '/ops/fee'
    | '/ops/occupancy'
    | '/ops/sla'
    | '/ops/work-orders'
    | '/saas/audit'
    | '/saas/billing'
    | '/saas/cai-dat'
    | '/saas/feature-flags'
    | '/saas/incidents'
    | '/saas/leads'
    | '/saas/plans'
    | '/saas/projects'
    | '/saas/tenants'
    | '/saas/users'
    | '/suc-khoe/quan-ly'
    | '/admin/'
    | '/bql/'
    | '/console/'
    | '/family/'
    | '/ops/'
    | '/saas/'
    | '/security/'
    | '/console/metrics/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bao-an'
    | '/cham-soc-ong-ba'
    | '/chi-tieu'
    | '/con-cai'
    | '/cong-dong'
    | '/dashboard'
    | '/demo'
    | '/demo-login'
    | '/dich-vu'
    | '/du-lich'
    | '/forgot-password'
    | '/gia-dinh'
    | '/home'
    | '/ky-niem-gia-dinh'
    | '/lich-gia-dinh'
    | '/lien-he'
    | '/login'
    | '/portal'
    | '/qr-vao-ra'
    | '/quan-ly-giup-viec'
    | '/reset-password'
    | '/suc-khoe'
    | '/tai-khoan'
    | '/thong-bao'
    | '/thuc-pham'
    | '/workspaces'
    | '/admin/audit'
    | '/admin/calendar'
    | '/admin/elderly-care'
    | '/admin/family'
    | '/admin/helpers'
    | '/admin/memories'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/super'
    | '/admin/users'
    | '/bql/an-ninh'
    | '/bql/bao-cao'
    | '/bql/bao-tri'
    | '/bql/cai-dat'
    | '/bql/can-ho'
    | '/bql/cu-dan'
    | '/bql/du-an'
    | '/bql/ho-gia-dinh'
    | '/bql/khach-xe'
    | '/bql/nhan-su'
    | '/bql/phan-anh'
    | '/bql/phi-dich-vu'
    | '/bql/su-co'
    | '/bql/thanh-toan'
    | '/bql/thong-bao'
    | '/bql/toa-nha'
    | '/bql/yeu-cau'
    | '/cai-dat/thong-bao'
    | '/cham-soc-ong-ba/nhat-ky'
    | '/chi-tieu/scan'
    | '/ops/complaints'
    | '/ops/fee'
    | '/ops/occupancy'
    | '/ops/sla'
    | '/ops/work-orders'
    | '/saas/audit'
    | '/saas/billing'
    | '/saas/cai-dat'
    | '/saas/feature-flags'
    | '/saas/incidents'
    | '/saas/leads'
    | '/saas/plans'
    | '/saas/projects'
    | '/saas/tenants'
    | '/saas/users'
    | '/suc-khoe/quan-ly'
    | '/admin'
    | '/bql'
    | '/console'
    | '/family'
    | '/ops'
    | '/saas'
    | '/security'
    | '/console/metrics/$key'
  id:
    | '__root__'
    | '/'
    | '/bao-an'
    | '/bql'
    | '/cham-soc-ong-ba'
    | '/chi-tieu'
    | '/con-cai'
    | '/cong-dong'
    | '/console'
    | '/dashboard'
    | '/demo'
    | '/demo-login'
    | '/dich-vu'
    | '/du-lich'
    | '/family'
    | '/forgot-password'
    | '/gia-dinh'
    | '/home'
    | '/ky-niem-gia-dinh'
    | '/lich-gia-dinh'
    | '/lien-he'
    | '/login'
    | '/ops'
    | '/portal'
    | '/qr-vao-ra'
    | '/quan-ly-giup-viec'
    | '/reset-password'
    | '/saas'
    | '/security'
    | '/suc-khoe'
    | '/tai-khoan'
    | '/thong-bao'
    | '/thuc-pham'
    | '/workspaces'
    | '/admin/audit'
    | '/admin/calendar'
    | '/admin/elderly-care'
    | '/admin/family'
    | '/admin/helpers'
    | '/admin/memories'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/super'
    | '/admin/users'
    | '/bql/an-ninh'
    | '/bql/bao-cao'
    | '/bql/bao-tri'
    | '/bql/cai-dat'
    | '/bql/can-ho'
    | '/bql/cu-dan'
    | '/bql/du-an'
    | '/bql/ho-gia-dinh'
    | '/bql/khach-xe'
    | '/bql/nhan-su'
    | '/bql/phan-anh'
    | '/bql/phi-dich-vu'
    | '/bql/su-co'
    | '/bql/thanh-toan'
    | '/bql/thong-bao'
    | '/bql/toa-nha'
    | '/bql/yeu-cau'
    | '/cai-dat/thong-bao'
    | '/cham-soc-ong-ba/nhat-ky'
    | '/chi-tieu_/scan'
    | '/ops/complaints'
    | '/ops/fee'
    | '/ops/occupancy'
    | '/ops/sla'
    | '/ops/work-orders'
    | '/saas/audit'
    | '/saas/billing'
    | '/saas/cai-dat'
    | '/saas/feature-flags'
    | '/saas/incidents'
    | '/saas/leads'
    | '/saas/plans'
    | '/saas/projects'
    | '/saas/tenants'
    | '/saas/users'
    | '/suc-khoe/quan-ly'
    | '/admin/'
    | '/bql/'
    | '/console/'
    | '/family/'
    | '/ops/'
    | '/saas/'
    | '/security/'
    | '/console/metrics/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoAnRoute: typeof BaoAnRoute
  BqlRoute: typeof BqlRouteWithChildren
  ChamSocOngBaRoute: typeof ChamSocOngBaRouteWithChildren
  ChiTieuRoute: typeof ChiTieuRoute
  ConCaiRoute: typeof ConCaiRoute
  CongDongRoute: typeof CongDongRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DemoLoginRoute: typeof DemoLoginRoute
  DichVuRoute: typeof DichVuRoute
  DuLichRoute: typeof DuLichRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GiaDinhRoute: typeof GiaDinhRoute
  GuardRoute: typeof GuardRouteWithChildren
  HomeRoute: typeof HomeRoute
  KyNiemGiaDinhRoute: typeof KyNiemGiaDinhRoute
  LichGiaDinhRoute: typeof LichGiaDinhRoute
  LienHeRoute: typeof LienHeRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  PortalRoute: typeof PortalRoute
  QrVaoRaRoute: typeof QrVaoRaRoute
  QuanLyGiupViecRoute: typeof QuanLyGiupViecRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaasRoute: typeof SaasRouteWithChildren
  SecurityRoute: typeof SecurityRouteWithChildren
  SucKhoeRoute: typeof SucKhoeRouteWithChildren
  TaiKhoanRoute: typeof TaiKhoanRoute
  ThongBaoRoute: typeof ThongBaoRoute
  ThucPhamRoute: typeof ThucPhamRoute
  WorkspacesRoute: typeof WorkspacesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminElderlyCareRoute: typeof AdminElderlyCareRoute
  AdminFamilyRoute: typeof AdminFamilyRoute
  AdminHelpersRoute: typeof AdminHelpersRoute
  AdminMemoriesRoute: typeof AdminMemoriesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSuperRoute: typeof AdminSuperRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CaiDatThongBaoRoute: typeof CaiDatThongBaoRoute
  ChiTieuScanRoute: typeof ChiTieuScanRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thuc-pham': {
      id: '/thuc-pham'
      path: '/thuc-pham'
      fullPath: '/thuc-pham'
      preLoaderRoute: typeof ThucPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thong-bao': {
      id: '/thong-bao'
      path: '/thong-bao'
      fullPath: '/thong-bao'
      preLoaderRoute: typeof ThongBaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suc-khoe': {
      id: '/suc-khoe'
      path: '/suc-khoe'
      fullPath: '/suc-khoe'
      preLoaderRoute: typeof SucKhoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly-giup-viec': {
      id: '/quan-ly-giup-viec'
      path: '/quan-ly-giup-viec'
      fullPath: '/quan-ly-giup-viec'
      preLoaderRoute: typeof QuanLyGiupViecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-vao-ra': {
      id: '/qr-vao-ra'
      path: '/qr-vao-ra'
      fullPath: '/qr-vao-ra'
      preLoaderRoute: typeof QrVaoRaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich-gia-dinh': {
      id: '/lich-gia-dinh'
      path: '/lich-gia-dinh'
      fullPath: '/lich-gia-dinh'
      preLoaderRoute: typeof LichGiaDinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ky-niem-gia-dinh': {
      id: '/ky-niem-gia-dinh'
      path: '/ky-niem-gia-dinh'
      fullPath: '/ky-niem-gia-dinh'
      preLoaderRoute: typeof KyNiemGiaDinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gia-dinh': {
      id: '/gia-dinh'
      path: '/gia-dinh'
      fullPath: '/gia-dinh'
      preLoaderRoute: typeof GiaDinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guard': {
      id: '/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof GuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-lich': {
      id: '/du-lich'
      path: '/du-lich'
      fullPath: '/du-lich'
      preLoaderRoute: typeof DuLichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu': {
      id: '/dich-vu'
      path: '/dich-vu'
      fullPath: '/dich-vu'
      preLoaderRoute: typeof DichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-login': {
      id: '/demo-login'
      path: '/demo-login'
      fullPath: '/demo-login'
      preLoaderRoute: typeof DemoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-dong': {
      id: '/cong-dong'
      path: '/cong-dong'
      fullPath: '/cong-dong'
      preLoaderRoute: typeof CongDongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/con-cai': {
      id: '/con-cai'
      path: '/con-cai'
      fullPath: '/con-cai'
      preLoaderRoute: typeof ConCaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-tieu': {
      id: '/chi-tieu'
      path: '/chi-tieu'
      fullPath: '/chi-tieu'
      preLoaderRoute: typeof ChiTieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cham-soc-ong-ba': {
      id: '/cham-soc-ong-ba'
      path: '/cham-soc-ong-ba'
      fullPath: '/cham-soc-ong-ba'
      preLoaderRoute: typeof ChamSocOngBaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bql': {
      id: '/bql'
      path: '/bql'
      fullPath: '/bql'
      preLoaderRoute: typeof BqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-an': {
      id: '/bao-an'
      path: '/bao-an'
      fullPath: '/bao-an'
      preLoaderRoute: typeof BaoAnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/guard/': {
      id: '/guard/'
      path: '/'
      fullPath: '/guard/'
      preLoaderRoute: typeof GuardIndexRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/patrol': {
      id: '/guard/patrol'
      path: '/patrol'
      fullPath: '/guard/patrol'
      preLoaderRoute: typeof GuardPatrolRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/scan': {
      id: '/guard/scan'
      path: '/scan'
      fullPath: '/guard/scan'
      preLoaderRoute: typeof GuardScanRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/tasks': {
      id: '/guard/tasks'
      path: '/tasks'
      fullPath: '/guard/tasks'
      preLoaderRoute: typeof GuardTasksRouteImport
      parentRoute: typeof GuardRoute
    }
    '/guard/me': {
      id: '/guard/me'
      path: '/me'
      fullPath: '/guard/me'
      preLoaderRoute: typeof GuardMeRouteImport
      parentRoute: typeof GuardRoute
    }
    '/saas/': {
      id: '/saas/'
      path: '/'
      fullPath: '/saas/'
      preLoaderRoute: typeof SaasIndexRouteImport
      parentRoute: typeof SaasRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/family/': {
      id: '/family/'
      path: '/'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/bql/': {
      id: '/bql/'
      path: '/'
      fullPath: '/bql/'
      preLoaderRoute: typeof BqlIndexRouteImport
      parentRoute: typeof BqlRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suc-khoe/quan-ly': {
      id: '/suc-khoe/quan-ly'
      path: '/quan-ly'
      fullPath: '/suc-khoe/quan-ly'
      preLoaderRoute: typeof SucKhoeQuanLyRouteImport
      parentRoute: typeof SucKhoeRoute
    }
    '/saas/users': {
      id: '/saas/users'
      path: '/users'
      fullPath: '/saas/users'
      preLoaderRoute: typeof SaasUsersRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/tenants': {
      id: '/saas/tenants'
      path: '/tenants'
      fullPath: '/saas/tenants'
      preLoaderRoute: typeof SaasTenantsRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/projects': {
      id: '/saas/projects'
      path: '/projects'
      fullPath: '/saas/projects'
      preLoaderRoute: typeof SaasProjectsRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/plans': {
      id: '/saas/plans'
      path: '/plans'
      fullPath: '/saas/plans'
      preLoaderRoute: typeof SaasPlansRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/leads': {
      id: '/saas/leads'
      path: '/leads'
      fullPath: '/saas/leads'
      preLoaderRoute: typeof SaasLeadsRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/incidents': {
      id: '/saas/incidents'
      path: '/incidents'
      fullPath: '/saas/incidents'
      preLoaderRoute: typeof SaasIncidentsRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/feature-flags': {
      id: '/saas/feature-flags'
      path: '/feature-flags'
      fullPath: '/saas/feature-flags'
      preLoaderRoute: typeof SaasFeatureFlagsRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/cai-dat': {
      id: '/saas/cai-dat'
      path: '/cai-dat'
      fullPath: '/saas/cai-dat'
      preLoaderRoute: typeof SaasCaiDatRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/billing': {
      id: '/saas/billing'
      path: '/billing'
      fullPath: '/saas/billing'
      preLoaderRoute: typeof SaasBillingRouteImport
      parentRoute: typeof SaasRoute
    }
    '/saas/audit': {
      id: '/saas/audit'
      path: '/audit'
      fullPath: '/saas/audit'
      preLoaderRoute: typeof SaasAuditRouteImport
      parentRoute: typeof SaasRoute
    }
    '/ops/work-orders': {
      id: '/ops/work-orders'
      path: '/work-orders'
      fullPath: '/ops/work-orders'
      preLoaderRoute: typeof OpsWorkOrdersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/sla': {
      id: '/ops/sla'
      path: '/sla'
      fullPath: '/ops/sla'
      preLoaderRoute: typeof OpsSlaRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/occupancy': {
      id: '/ops/occupancy'
      path: '/occupancy'
      fullPath: '/ops/occupancy'
      preLoaderRoute: typeof OpsOccupancyRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/fee': {
      id: '/ops/fee'
      path: '/fee'
      fullPath: '/ops/fee'
      preLoaderRoute: typeof OpsFeeRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/complaints': {
      id: '/ops/complaints'
      path: '/complaints'
      fullPath: '/ops/complaints'
      preLoaderRoute: typeof OpsComplaintsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/chi-tieu_/scan': {
      id: '/chi-tieu_/scan'
      path: '/chi-tieu/scan'
      fullPath: '/chi-tieu/scan'
      preLoaderRoute: typeof ChiTieuScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cham-soc-ong-ba/nhat-ky': {
      id: '/cham-soc-ong-ba/nhat-ky'
      path: '/nhat-ky'
      fullPath: '/cham-soc-ong-ba/nhat-ky'
      preLoaderRoute: typeof ChamSocOngBaNhatKyRouteImport
      parentRoute: typeof ChamSocOngBaRoute
    }
    '/cai-dat/thong-bao': {
      id: '/cai-dat/thong-bao'
      path: '/cai-dat/thong-bao'
      fullPath: '/cai-dat/thong-bao'
      preLoaderRoute: typeof CaiDatThongBaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bql/yeu-cau': {
      id: '/bql/yeu-cau'
      path: '/yeu-cau'
      fullPath: '/bql/yeu-cau'
      preLoaderRoute: typeof BqlYeuCauRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/toa-nha': {
      id: '/bql/toa-nha'
      path: '/toa-nha'
      fullPath: '/bql/toa-nha'
      preLoaderRoute: typeof BqlToaNhaRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/thong-bao': {
      id: '/bql/thong-bao'
      path: '/thong-bao'
      fullPath: '/bql/thong-bao'
      preLoaderRoute: typeof BqlThongBaoRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/thanh-toan': {
      id: '/bql/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/bql/thanh-toan'
      preLoaderRoute: typeof BqlThanhToanRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/su-co': {
      id: '/bql/su-co'
      path: '/su-co'
      fullPath: '/bql/su-co'
      preLoaderRoute: typeof BqlSuCoRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/phi-dich-vu': {
      id: '/bql/phi-dich-vu'
      path: '/phi-dich-vu'
      fullPath: '/bql/phi-dich-vu'
      preLoaderRoute: typeof BqlPhiDichVuRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/phan-anh': {
      id: '/bql/phan-anh'
      path: '/phan-anh'
      fullPath: '/bql/phan-anh'
      preLoaderRoute: typeof BqlPhanAnhRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/nhan-su': {
      id: '/bql/nhan-su'
      path: '/nhan-su'
      fullPath: '/bql/nhan-su'
      preLoaderRoute: typeof BqlNhanSuRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/khach-xe': {
      id: '/bql/khach-xe'
      path: '/khach-xe'
      fullPath: '/bql/khach-xe'
      preLoaderRoute: typeof BqlKhachXeRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/ho-gia-dinh': {
      id: '/bql/ho-gia-dinh'
      path: '/ho-gia-dinh'
      fullPath: '/bql/ho-gia-dinh'
      preLoaderRoute: typeof BqlHoGiaDinhRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/du-an': {
      id: '/bql/du-an'
      path: '/du-an'
      fullPath: '/bql/du-an'
      preLoaderRoute: typeof BqlDuAnRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/cu-dan': {
      id: '/bql/cu-dan'
      path: '/cu-dan'
      fullPath: '/bql/cu-dan'
      preLoaderRoute: typeof BqlCuDanRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/can-ho': {
      id: '/bql/can-ho'
      path: '/can-ho'
      fullPath: '/bql/can-ho'
      preLoaderRoute: typeof BqlCanHoRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/cai-dat': {
      id: '/bql/cai-dat'
      path: '/cai-dat'
      fullPath: '/bql/cai-dat'
      preLoaderRoute: typeof BqlCaiDatRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/bao-tri': {
      id: '/bql/bao-tri'
      path: '/bao-tri'
      fullPath: '/bql/bao-tri'
      preLoaderRoute: typeof BqlBaoTriRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/bao-cao': {
      id: '/bql/bao-cao'
      path: '/bao-cao'
      fullPath: '/bql/bao-cao'
      preLoaderRoute: typeof BqlBaoCaoRouteImport
      parentRoute: typeof BqlRoute
    }
    '/bql/an-ninh': {
      id: '/bql/an-ninh'
      path: '/an-ninh'
      fullPath: '/bql/an-ninh'
      preLoaderRoute: typeof BqlAnNinhRouteImport
      parentRoute: typeof BqlRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/super': {
      id: '/admin/super'
      path: '/admin/super'
      fullPath: '/admin/super'
      preLoaderRoute: typeof AdminSuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/memories': {
      id: '/admin/memories'
      path: '/admin/memories'
      fullPath: '/admin/memories'
      preLoaderRoute: typeof AdminMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/helpers': {
      id: '/admin/helpers'
      path: '/admin/helpers'
      fullPath: '/admin/helpers'
      preLoaderRoute: typeof AdminHelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/family': {
      id: '/admin/family'
      path: '/admin/family'
      fullPath: '/admin/family'
      preLoaderRoute: typeof AdminFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elderly-care': {
      id: '/admin/elderly-care'
      path: '/admin/elderly-care'
      fullPath: '/admin/elderly-care'
      preLoaderRoute: typeof AdminElderlyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/metrics/$key': {
      id: '/console/metrics/$key'
      path: '/metrics/$key'
      fullPath: '/console/metrics/$key'
      preLoaderRoute: typeof ConsoleMetricsKeyRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface BqlRouteChildren {
  BqlAnNinhRoute: typeof BqlAnNinhRoute
  BqlBaoCaoRoute: typeof BqlBaoCaoRoute
  BqlBaoTriRoute: typeof BqlBaoTriRoute
  BqlCaiDatRoute: typeof BqlCaiDatRoute
  BqlCanHoRoute: typeof BqlCanHoRoute
  BqlCuDanRoute: typeof BqlCuDanRoute
  BqlDuAnRoute: typeof BqlDuAnRoute
  BqlHoGiaDinhRoute: typeof BqlHoGiaDinhRoute
  BqlKhachXeRoute: typeof BqlKhachXeRoute
  BqlNhanSuRoute: typeof BqlNhanSuRoute
  BqlPhanAnhRoute: typeof BqlPhanAnhRoute
  BqlPhiDichVuRoute: typeof BqlPhiDichVuRoute
  BqlSuCoRoute: typeof BqlSuCoRoute
  BqlThanhToanRoute: typeof BqlThanhToanRoute
  BqlThongBaoRoute: typeof BqlThongBaoRoute
  BqlToaNhaRoute: typeof BqlToaNhaRoute
  BqlYeuCauRoute: typeof BqlYeuCauRoute
  BqlIndexRoute: typeof BqlIndexRoute
}

const BqlRouteChildren: BqlRouteChildren = {
  BqlAnNinhRoute: BqlAnNinhRoute,
  BqlBaoCaoRoute: BqlBaoCaoRoute,
  BqlBaoTriRoute: BqlBaoTriRoute,
  BqlCaiDatRoute: BqlCaiDatRoute,
  BqlCanHoRoute: BqlCanHoRoute,
  BqlCuDanRoute: BqlCuDanRoute,
  BqlDuAnRoute: BqlDuAnRoute,
  BqlHoGiaDinhRoute: BqlHoGiaDinhRoute,
  BqlKhachXeRoute: BqlKhachXeRoute,
  BqlNhanSuRoute: BqlNhanSuRoute,
  BqlPhanAnhRoute: BqlPhanAnhRoute,
  BqlPhiDichVuRoute: BqlPhiDichVuRoute,
  BqlSuCoRoute: BqlSuCoRoute,
  BqlThanhToanRoute: BqlThanhToanRoute,
  BqlThongBaoRoute: BqlThongBaoRoute,
  BqlToaNhaRoute: BqlToaNhaRoute,
  BqlYeuCauRoute: BqlYeuCauRoute,
  BqlIndexRoute: BqlIndexRoute,
}

const BqlRouteWithChildren = BqlRoute._addFileChildren(BqlRouteChildren)

interface ChamSocOngBaRouteChildren {
  ChamSocOngBaNhatKyRoute: typeof ChamSocOngBaNhatKyRoute
}

const ChamSocOngBaRouteChildren: ChamSocOngBaRouteChildren = {
  ChamSocOngBaNhatKyRoute: ChamSocOngBaNhatKyRoute,
}

const ChamSocOngBaRouteWithChildren = ChamSocOngBaRoute._addFileChildren(
  ChamSocOngBaRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleMetricsKeyRoute: typeof ConsoleMetricsKeyRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleMetricsKeyRoute: ConsoleMetricsKeyRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface FamilyRouteChildren {
  FamilyIndexRoute: typeof FamilyIndexRoute
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyIndexRoute: FamilyIndexRoute,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

interface OpsRouteChildren {
  OpsComplaintsRoute: typeof OpsComplaintsRoute
  OpsFeeRoute: typeof OpsFeeRoute
  OpsOccupancyRoute: typeof OpsOccupancyRoute
  OpsSlaRoute: typeof OpsSlaRoute
  OpsWorkOrdersRoute: typeof OpsWorkOrdersRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsComplaintsRoute: OpsComplaintsRoute,
  OpsFeeRoute: OpsFeeRoute,
  OpsOccupancyRoute: OpsOccupancyRoute,
  OpsSlaRoute: OpsSlaRoute,
  OpsWorkOrdersRoute: OpsWorkOrdersRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface SaasRouteChildren {
  SaasAuditRoute: typeof SaasAuditRoute
  SaasBillingRoute: typeof SaasBillingRoute
  SaasCaiDatRoute: typeof SaasCaiDatRoute
  SaasFeatureFlagsRoute: typeof SaasFeatureFlagsRoute
  SaasIncidentsRoute: typeof SaasIncidentsRoute
  SaasLeadsRoute: typeof SaasLeadsRoute
  SaasPlansRoute: typeof SaasPlansRoute
  SaasProjectsRoute: typeof SaasProjectsRoute
  SaasTenantsRoute: typeof SaasTenantsRoute
  SaasUsersRoute: typeof SaasUsersRoute
  SaasIndexRoute: typeof SaasIndexRoute
}

const SaasRouteChildren: SaasRouteChildren = {
  SaasAuditRoute: SaasAuditRoute,
  SaasBillingRoute: SaasBillingRoute,
  SaasCaiDatRoute: SaasCaiDatRoute,
  SaasFeatureFlagsRoute: SaasFeatureFlagsRoute,
  SaasIncidentsRoute: SaasIncidentsRoute,
  SaasLeadsRoute: SaasLeadsRoute,
  SaasPlansRoute: SaasPlansRoute,
  SaasProjectsRoute: SaasProjectsRoute,
  SaasTenantsRoute: SaasTenantsRoute,
  SaasUsersRoute: SaasUsersRoute,
  SaasIndexRoute: SaasIndexRoute,
}

const SaasRouteWithChildren = SaasRoute._addFileChildren(SaasRouteChildren)

interface GuardRouteChildren {
  GuardMeRoute: typeof GuardMeRoute
  GuardTasksRoute: typeof GuardTasksRoute
  GuardScanRoute: typeof GuardScanRoute
  GuardPatrolRoute: typeof GuardPatrolRoute
  GuardIndexRoute: typeof GuardIndexRoute
}

const GuardRouteChildren: GuardRouteChildren = {
  GuardMeRoute: GuardMeRoute,
  GuardTasksRoute: GuardTasksRoute,
  GuardScanRoute: GuardScanRoute,
  GuardPatrolRoute: GuardPatrolRoute,
  GuardIndexRoute: GuardIndexRoute,
}

const GuardRouteWithChildren =
  GuardRoute._addFileChildren(GuardRouteChildren)

interface SecurityRouteChildren {
  SecurityIndexRoute: typeof SecurityIndexRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityIndexRoute: SecurityIndexRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

interface SucKhoeRouteChildren {
  SucKhoeQuanLyRoute: typeof SucKhoeQuanLyRoute
}

const SucKhoeRouteChildren: SucKhoeRouteChildren = {
  SucKhoeQuanLyRoute: SucKhoeQuanLyRoute,
}

const SucKhoeRouteWithChildren =
  SucKhoeRoute._addFileChildren(SucKhoeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoAnRoute: BaoAnRoute,
  BqlRoute: BqlRouteWithChildren,
  ChamSocOngBaRoute: ChamSocOngBaRouteWithChildren,
  ChiTieuRoute: ChiTieuRoute,
  ConCaiRoute: ConCaiRoute,
  CongDongRoute: CongDongRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DemoLoginRoute: DemoLoginRoute,
  DichVuRoute: DichVuRoute,
  DuLichRoute: DuLichRoute,
  FamilyRoute: FamilyRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GiaDinhRoute: GiaDinhRoute,
  GuardRoute: GuardRouteWithChildren,
  HomeRoute: HomeRoute,
  KyNiemGiaDinhRoute: KyNiemGiaDinhRoute,
  LichGiaDinhRoute: LichGiaDinhRoute,
  LienHeRoute: LienHeRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  PortalRoute: PortalRoute,
  QrVaoRaRoute: QrVaoRaRoute,
  QuanLyGiupViecRoute: QuanLyGiupViecRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaasRoute: SaasRouteWithChildren,
  SecurityRoute: SecurityRouteWithChildren,
  SucKhoeRoute: SucKhoeRouteWithChildren,
  TaiKhoanRoute: TaiKhoanRoute,
  ThongBaoRoute: ThongBaoRoute,
  ThucPhamRoute: ThucPhamRoute,
  WorkspacesRoute: WorkspacesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminElderlyCareRoute: AdminElderlyCareRoute,
  AdminFamilyRoute: AdminFamilyRoute,
  AdminHelpersRoute: AdminHelpersRoute,
  AdminMemoriesRoute: AdminMemoriesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSuperRoute: AdminSuperRoute,
  AdminUsersRoute: AdminUsersRoute,
  CaiDatThongBaoRoute: CaiDatThongBaoRoute,
  ChiTieuScanRoute: ChiTieuScanRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
