/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThucPhamRouteImport } from './routes/thuc-pham'
import { Route as ThongBaoRouteImport } from './routes/thong-bao'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as SucKhoeRouteImport } from './routes/suc-khoe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuanLyGiupViecRouteImport } from './routes/quan-ly-giup-viec'
import { Route as QrVaoRaRouteImport } from './routes/qr-vao-ra'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as LichGiaDinhRouteImport } from './routes/lich-gia-dinh'
import { Route as KyNiemGiaDinhRouteImport } from './routes/ky-niem-gia-dinh'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GiaDinhRouteImport } from './routes/gia-dinh'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DuLichRouteImport } from './routes/du-lich'
import { Route as DichVuRouteImport } from './routes/dich-vu'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CongDongRouteImport } from './routes/cong-dong'
import { Route as ConCaiRouteImport } from './routes/con-cai'
import { Route as ChiTieuRouteImport } from './routes/chi-tieu'
import { Route as ChamSocOngBaRouteImport } from './routes/cham-soc-ong-ba'
import { Route as BaoAnRouteImport } from './routes/bao-an'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SucKhoeQuanLyRouteImport } from './routes/suc-khoe.quan-ly'
import { Route as ChiTieuScanRouteImport } from './routes/chi-tieu_.scan'
import { Route as ChamSocOngBaNhatKyRouteImport } from './routes/cham-soc-ong-ba.nhat-ky'
import { Route as CaiDatThongBaoRouteImport } from './routes/cai-dat.thong-bao'

const ThucPhamRoute = ThucPhamRouteImport.update({
  id: '/thuc-pham',
  path: '/thuc-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const ThongBaoRoute = ThongBaoRouteImport.update({
  id: '/thong-bao',
  path: '/thong-bao',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const SucKhoeRoute = SucKhoeRouteImport.update({
  id: '/suc-khoe',
  path: '/suc-khoe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyGiupViecRoute = QuanLyGiupViecRouteImport.update({
  id: '/quan-ly-giup-viec',
  path: '/quan-ly-giup-viec',
  getParentRoute: () => rootRouteImport,
} as any)
const QrVaoRaRoute = QrVaoRaRouteImport.update({
  id: '/qr-vao-ra',
  path: '/qr-vao-ra',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const LichGiaDinhRoute = LichGiaDinhRouteImport.update({
  id: '/lich-gia-dinh',
  path: '/lich-gia-dinh',
  getParentRoute: () => rootRouteImport,
} as any)
const KyNiemGiaDinhRoute = KyNiemGiaDinhRouteImport.update({
  id: '/ky-niem-gia-dinh',
  path: '/ky-niem-gia-dinh',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaDinhRoute = GiaDinhRouteImport.update({
  id: '/gia-dinh',
  path: '/gia-dinh',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DuLichRoute = DuLichRouteImport.update({
  id: '/du-lich',
  path: '/du-lich',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuRoute = DichVuRouteImport.update({
  id: '/dich-vu',
  path: '/dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CongDongRoute = CongDongRouteImport.update({
  id: '/cong-dong',
  path: '/cong-dong',
  getParentRoute: () => rootRouteImport,
} as any)
const ConCaiRoute = ConCaiRouteImport.update({
  id: '/con-cai',
  path: '/con-cai',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiTieuRoute = ChiTieuRouteImport.update({
  id: '/chi-tieu',
  path: '/chi-tieu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamSocOngBaRoute = ChamSocOngBaRouteImport.update({
  id: '/cham-soc-ong-ba',
  path: '/cham-soc-ong-ba',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoAnRoute = BaoAnRouteImport.update({
  id: '/bao-an',
  path: '/bao-an',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SucKhoeQuanLyRoute = SucKhoeQuanLyRouteImport.update({
  id: '/quan-ly',
  path: '/quan-ly',
  getParentRoute: () => SucKhoeRoute,
} as any)
const ChiTieuScanRoute = ChiTieuScanRouteImport.update({
  id: '/chi-tieu_/scan',
  path: '/chi-tieu/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamSocOngBaNhatKyRoute = ChamSocOngBaNhatKyRouteImport.update({
  id: '/nhat-ky',
  path: '/nhat-ky',
  getParentRoute: () => ChamSocOngBaRoute,
} as any)
const CaiDatThongBaoRoute = CaiDatThongBaoRouteImport.update({
  id: '/cai-dat/thong-bao',
  path: '/cai-dat/thong-bao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bao-an': typeof BaoAnRoute
  '/cham-soc-ong-ba': typeof ChamSocOngBaRouteWithChildren
  '/chi-tieu': typeof ChiTieuRoute
  '/con-cai': typeof ConCaiRoute
  '/cong-dong': typeof CongDongRoute
  '/dashboard': typeof DashboardRoute
  '/dich-vu': typeof DichVuRoute
  '/du-lich': typeof DuLichRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gia-dinh': typeof GiaDinhRoute
  '/home': typeof HomeRoute
  '/ky-niem-gia-dinh': typeof KyNiemGiaDinhRoute
  '/lich-gia-dinh': typeof LichGiaDinhRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/qr-vao-ra': typeof QrVaoRaRoute
  '/quan-ly-giup-viec': typeof QuanLyGiupViecRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suc-khoe': typeof SucKhoeRouteWithChildren
  '/tai-khoan': typeof TaiKhoanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/cai-dat/thong-bao': typeof CaiDatThongBaoRoute
  '/cham-soc-ong-ba/nhat-ky': typeof ChamSocOngBaNhatKyRoute
  '/chi-tieu/scan': typeof ChiTieuScanRoute
  '/suc-khoe/quan-ly': typeof SucKhoeQuanLyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bao-an': typeof BaoAnRoute
  '/cham-soc-ong-ba': typeof ChamSocOngBaRouteWithChildren
  '/chi-tieu': typeof ChiTieuRoute
  '/con-cai': typeof ConCaiRoute
  '/cong-dong': typeof CongDongRoute
  '/dashboard': typeof DashboardRoute
  '/dich-vu': typeof DichVuRoute
  '/du-lich': typeof DuLichRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gia-dinh': typeof GiaDinhRoute
  '/home': typeof HomeRoute
  '/ky-niem-gia-dinh': typeof KyNiemGiaDinhRoute
  '/lich-gia-dinh': typeof LichGiaDinhRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/qr-vao-ra': typeof QrVaoRaRoute
  '/quan-ly-giup-viec': typeof QuanLyGiupViecRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suc-khoe': typeof SucKhoeRouteWithChildren
  '/tai-khoan': typeof TaiKhoanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/cai-dat/thong-bao': typeof CaiDatThongBaoRoute
  '/cham-soc-ong-ba/nhat-ky': typeof ChamSocOngBaNhatKyRoute
  '/chi-tieu/scan': typeof ChiTieuScanRoute
  '/suc-khoe/quan-ly': typeof SucKhoeQuanLyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bao-an': typeof BaoAnRoute
  '/cham-soc-ong-ba': typeof ChamSocOngBaRouteWithChildren
  '/chi-tieu': typeof ChiTieuRoute
  '/con-cai': typeof ConCaiRoute
  '/cong-dong': typeof CongDongRoute
  '/dashboard': typeof DashboardRoute
  '/dich-vu': typeof DichVuRoute
  '/du-lich': typeof DuLichRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gia-dinh': typeof GiaDinhRoute
  '/home': typeof HomeRoute
  '/ky-niem-gia-dinh': typeof KyNiemGiaDinhRoute
  '/lich-gia-dinh': typeof LichGiaDinhRoute
  '/lien-he': typeof LienHeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/qr-vao-ra': typeof QrVaoRaRoute
  '/quan-ly-giup-viec': typeof QuanLyGiupViecRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suc-khoe': typeof SucKhoeRouteWithChildren
  '/tai-khoan': typeof TaiKhoanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thuc-pham': typeof ThucPhamRoute
  '/cai-dat/thong-bao': typeof CaiDatThongBaoRoute
  '/cham-soc-ong-ba/nhat-ky': typeof ChamSocOngBaNhatKyRoute
  '/chi-tieu_/scan': typeof ChiTieuScanRoute
  '/suc-khoe/quan-ly': typeof SucKhoeQuanLyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bao-an'
    | '/cham-soc-ong-ba'
    | '/chi-tieu'
    | '/con-cai'
    | '/cong-dong'
    | '/dashboard'
    | '/dich-vu'
    | '/du-lich'
    | '/forgot-password'
    | '/gia-dinh'
    | '/home'
    | '/ky-niem-gia-dinh'
    | '/lich-gia-dinh'
    | '/lien-he'
    | '/login'
    | '/portal'
    | '/qr-vao-ra'
    | '/quan-ly-giup-viec'
    | '/reset-password'
    | '/suc-khoe'
    | '/tai-khoan'
    | '/thong-bao'
    | '/thuc-pham'
    | '/cai-dat/thong-bao'
    | '/cham-soc-ong-ba/nhat-ky'
    | '/chi-tieu/scan'
    | '/suc-khoe/quan-ly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bao-an'
    | '/cham-soc-ong-ba'
    | '/chi-tieu'
    | '/con-cai'
    | '/cong-dong'
    | '/dashboard'
    | '/dich-vu'
    | '/du-lich'
    | '/forgot-password'
    | '/gia-dinh'
    | '/home'
    | '/ky-niem-gia-dinh'
    | '/lich-gia-dinh'
    | '/lien-he'
    | '/login'
    | '/portal'
    | '/qr-vao-ra'
    | '/quan-ly-giup-viec'
    | '/reset-password'
    | '/suc-khoe'
    | '/tai-khoan'
    | '/thong-bao'
    | '/thuc-pham'
    | '/cai-dat/thong-bao'
    | '/cham-soc-ong-ba/nhat-ky'
    | '/chi-tieu/scan'
    | '/suc-khoe/quan-ly'
  id:
    | '__root__'
    | '/'
    | '/bao-an'
    | '/cham-soc-ong-ba'
    | '/chi-tieu'
    | '/con-cai'
    | '/cong-dong'
    | '/dashboard'
    | '/dich-vu'
    | '/du-lich'
    | '/forgot-password'
    | '/gia-dinh'
    | '/home'
    | '/ky-niem-gia-dinh'
    | '/lich-gia-dinh'
    | '/lien-he'
    | '/login'
    | '/portal'
    | '/qr-vao-ra'
    | '/quan-ly-giup-viec'
    | '/reset-password'
    | '/suc-khoe'
    | '/tai-khoan'
    | '/thong-bao'
    | '/thuc-pham'
    | '/cai-dat/thong-bao'
    | '/cham-soc-ong-ba/nhat-ky'
    | '/chi-tieu_/scan'
    | '/suc-khoe/quan-ly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoAnRoute: typeof BaoAnRoute
  ChamSocOngBaRoute: typeof ChamSocOngBaRouteWithChildren
  ChiTieuRoute: typeof ChiTieuRoute
  ConCaiRoute: typeof ConCaiRoute
  CongDongRoute: typeof CongDongRoute
  DashboardRoute: typeof DashboardRoute
  DichVuRoute: typeof DichVuRoute
  DuLichRoute: typeof DuLichRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GiaDinhRoute: typeof GiaDinhRoute
  HomeRoute: typeof HomeRoute
  KyNiemGiaDinhRoute: typeof KyNiemGiaDinhRoute
  LichGiaDinhRoute: typeof LichGiaDinhRoute
  LienHeRoute: typeof LienHeRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  QrVaoRaRoute: typeof QrVaoRaRoute
  QuanLyGiupViecRoute: typeof QuanLyGiupViecRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SucKhoeRoute: typeof SucKhoeRouteWithChildren
  TaiKhoanRoute: typeof TaiKhoanRoute
  ThongBaoRoute: typeof ThongBaoRoute
  ThucPhamRoute: typeof ThucPhamRoute
  CaiDatThongBaoRoute: typeof CaiDatThongBaoRoute
  ChiTieuScanRoute: typeof ChiTieuScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thuc-pham': {
      id: '/thuc-pham'
      path: '/thuc-pham'
      fullPath: '/thuc-pham'
      preLoaderRoute: typeof ThucPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thong-bao': {
      id: '/thong-bao'
      path: '/thong-bao'
      fullPath: '/thong-bao'
      preLoaderRoute: typeof ThongBaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suc-khoe': {
      id: '/suc-khoe'
      path: '/suc-khoe'
      fullPath: '/suc-khoe'
      preLoaderRoute: typeof SucKhoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly-giup-viec': {
      id: '/quan-ly-giup-viec'
      path: '/quan-ly-giup-viec'
      fullPath: '/quan-ly-giup-viec'
      preLoaderRoute: typeof QuanLyGiupViecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-vao-ra': {
      id: '/qr-vao-ra'
      path: '/qr-vao-ra'
      fullPath: '/qr-vao-ra'
      preLoaderRoute: typeof QrVaoRaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich-gia-dinh': {
      id: '/lich-gia-dinh'
      path: '/lich-gia-dinh'
      fullPath: '/lich-gia-dinh'
      preLoaderRoute: typeof LichGiaDinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ky-niem-gia-dinh': {
      id: '/ky-niem-gia-dinh'
      path: '/ky-niem-gia-dinh'
      fullPath: '/ky-niem-gia-dinh'
      preLoaderRoute: typeof KyNiemGiaDinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gia-dinh': {
      id: '/gia-dinh'
      path: '/gia-dinh'
      fullPath: '/gia-dinh'
      preLoaderRoute: typeof GiaDinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-lich': {
      id: '/du-lich'
      path: '/du-lich'
      fullPath: '/du-lich'
      preLoaderRoute: typeof DuLichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu': {
      id: '/dich-vu'
      path: '/dich-vu'
      fullPath: '/dich-vu'
      preLoaderRoute: typeof DichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-dong': {
      id: '/cong-dong'
      path: '/cong-dong'
      fullPath: '/cong-dong'
      preLoaderRoute: typeof CongDongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/con-cai': {
      id: '/con-cai'
      path: '/con-cai'
      fullPath: '/con-cai'
      preLoaderRoute: typeof ConCaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-tieu': {
      id: '/chi-tieu'
      path: '/chi-tieu'
      fullPath: '/chi-tieu'
      preLoaderRoute: typeof ChiTieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cham-soc-ong-ba': {
      id: '/cham-soc-ong-ba'
      path: '/cham-soc-ong-ba'
      fullPath: '/cham-soc-ong-ba'
      preLoaderRoute: typeof ChamSocOngBaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-an': {
      id: '/bao-an'
      path: '/bao-an'
      fullPath: '/bao-an'
      preLoaderRoute: typeof BaoAnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suc-khoe/quan-ly': {
      id: '/suc-khoe/quan-ly'
      path: '/quan-ly'
      fullPath: '/suc-khoe/quan-ly'
      preLoaderRoute: typeof SucKhoeQuanLyRouteImport
      parentRoute: typeof SucKhoeRoute
    }
    '/chi-tieu_/scan': {
      id: '/chi-tieu_/scan'
      path: '/chi-tieu/scan'
      fullPath: '/chi-tieu/scan'
      preLoaderRoute: typeof ChiTieuScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cham-soc-ong-ba/nhat-ky': {
      id: '/cham-soc-ong-ba/nhat-ky'
      path: '/nhat-ky'
      fullPath: '/cham-soc-ong-ba/nhat-ky'
      preLoaderRoute: typeof ChamSocOngBaNhatKyRouteImport
      parentRoute: typeof ChamSocOngBaRoute
    }
    '/cai-dat/thong-bao': {
      id: '/cai-dat/thong-bao'
      path: '/cai-dat/thong-bao'
      fullPath: '/cai-dat/thong-bao'
      preLoaderRoute: typeof CaiDatThongBaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChamSocOngBaRouteChildren {
  ChamSocOngBaNhatKyRoute: typeof ChamSocOngBaNhatKyRoute
}

const ChamSocOngBaRouteChildren: ChamSocOngBaRouteChildren = {
  ChamSocOngBaNhatKyRoute: ChamSocOngBaNhatKyRoute,
}

const ChamSocOngBaRouteWithChildren = ChamSocOngBaRoute._addFileChildren(
  ChamSocOngBaRouteChildren,
)

interface SucKhoeRouteChildren {
  SucKhoeQuanLyRoute: typeof SucKhoeQuanLyRoute
}

const SucKhoeRouteChildren: SucKhoeRouteChildren = {
  SucKhoeQuanLyRoute: SucKhoeQuanLyRoute,
}

const SucKhoeRouteWithChildren =
  SucKhoeRoute._addFileChildren(SucKhoeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoAnRoute: BaoAnRoute,
  ChamSocOngBaRoute: ChamSocOngBaRouteWithChildren,
  ChiTieuRoute: ChiTieuRoute,
  ConCaiRoute: ConCaiRoute,
  CongDongRoute: CongDongRoute,
  DashboardRoute: DashboardRoute,
  DichVuRoute: DichVuRoute,
  DuLichRoute: DuLichRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GiaDinhRoute: GiaDinhRoute,
  HomeRoute: HomeRoute,
  KyNiemGiaDinhRoute: KyNiemGiaDinhRoute,
  LichGiaDinhRoute: LichGiaDinhRoute,
  LienHeRoute: LienHeRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  QrVaoRaRoute: QrVaoRaRoute,
  QuanLyGiupViecRoute: QuanLyGiupViecRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SucKhoeRoute: SucKhoeRouteWithChildren,
  TaiKhoanRoute: TaiKhoanRoute,
  ThongBaoRoute: ThongBaoRoute,
  ThucPhamRoute: ThucPhamRoute,
  CaiDatThongBaoRoute: CaiDatThongBaoRoute,
  ChiTieuScanRoute: ChiTieuScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
